disk:
  type: 'raw'
  path: '../target/disk_deployment.raw'
  size_mib: 512
dirs:
files:
- source: 'init.yaml'
  destination: '/usr/etc/init.yaml'
  uid: 0
  permissions: 0o400
  label: 'init_config'
- source: 'auditd.conf'
  destination: '/usr/etc/auditd/auditd.conf'
  uid: 0
  gid: 1
  permissions: 0o440
  label: 'auditd_config'
- source: 'auditd.rules'
  destination: '/usr/etc/auditd/auditd.rules'
  uid: 1
  permissions: 0o400
  label: 'auditd_rules'
